# Generated by Django 4.2.13 on 2024-07-05 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("image", models.ImageField(upload_to="book_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seen_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seen_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
