# Generated by Django 4.2.13 on 2024-07-11 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booksummaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookSummaryAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_time", models.DateTimeField(auto_now_add=True)),
                (
                    "book_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booksummaries.booksummary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
