# Generated by Django 4.2.13 on 2024-07-12 14:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booksummaries", "0003_bookpurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksummary",
            name="summary",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
