# Generated by Django 4.2.13 on 2024-07-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name="customuser", name="interests",),
        migrations.AlterField(
            model_name="customuser",
            name="nationality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("american", "American"),
                    ("canadian", "Canadian"),
                    ("british", "British"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="interests",
            field=models.ManyToManyField(blank=True, to="accounts.interest"),
        ),
    ]
