# Generated by Django 4.2.13 on 2024-07-05 08:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_interest_remove_customuser_interests_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="nationality",),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(
                choices=[
                    ("coding", "Coding"),
                    ("reading", "Reading"),
                    ("gaming", "Gaming"),
                    ("hiking", "Hiking"),
                ],
                max_length=50,
            ),
        ),
    ]
