# Generated by Django 4.2.13 on 2024-07-06 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="quote", name="updated_at",),
        migrations.AddField(
            model_name="quote",
            name="seen_by",
            field=models.ManyToManyField(
                blank=True, related_name="seen_quote", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
